### Criar disciplina
POST http://localhost:8000/rest/sistema/discipline/criar
Content-Type: application/json

{
  "name": "Matemática",
  "description": "Disciplina de matemática"
}

###

### Listar todas disciplinas
GET http://localhost:8000/rest/sistema/discipline/listar

###

### Buscar disciplina por ID
GET http://localhost:8000/rest/sistema/module/buscar/2

###

### Atualizar disciplina
PUT http://localhost:8000/rest/sistema/discipline/alterar/23
Content-Type: application/json

{
  "name": "Física",
  "description": "Disciplina de física"
}

###

### Remover disciplina
DELETE http://localhost:8000/rest/sistema/discipline/excluir/23
