### Criar disciplina
POST http://localhost:8000/rest/sistema/module/criar
Content-Type: application/json

{
  "disciplineId": "2",
  "title": "Matemática",
  "description": "Disciplina de matemática"
}

###

### Listar todas disciplinas
GET http://localhost:8000/rest/sistema/module/listar

###

### Buscar disciplina por ID
GET http://localhost:8000/rest/sistema/module/buscar/2

###

### Atualizar disciplina
PUT http://localhost:8000/rest/sistema/module/alterar/35
Content-Type: application/json

{
  "disciplineId": "1",
  "title": "Física",
  "description": "Disciplina de física"
}

###

### Remover disciplina
DELETE http://localhost:8000/rest/sistema/discipline/excluir/43
